export const radio_data = [
  {
    name: 'pixel radio',
    location: 'ru',
    genre: 'electronic',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Пилот FM',
    location: 'ru',
    genre: 'pop',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Love Radio',
    location: 'ru',
    genre: 'pop',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Дорожное',
    location: 'ru',
    genre: 'chanson',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Record',
    location: 'ru',
    genre: 'dance',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Dance FM',
    location: 'us',
    genre: 'dance',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'YO! FM',
    location: 'us',
    genre: 'hip hop',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Radio Ritmo',
    location: 'de',
    genre: 'dance',
    image: 'url',
    audio: 'url',
  },
  {
    name: 'Maximum FM',
    location: 'de',
    genre: 'adult pop',
    image: 'url',
    audio: 'url',
  },
]
